name: simple_music_player_2
description: "A new modern Flutter music player."
publish_to: 'none'
version: 1.7.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Audio
  just_audio: ^0.9.36
  just_audio_windows:
  equalizer_flutter: ^0.0.1 # Standard Android EQ wrapper

  # Metadata
  metadata_god: 1.1.0
  flutter_media_metadata: 1.0.0+1
  
  # Discord
  flutter_discord_rpc: ^1.0.0
  
  # Tools
  shared_preferences: ^2.2.2
  path: ^1.9.0
  file_picker: ^10.3.7
  package_info_plus: ^8.0.0

  # Parsing HTTP
  http: ^1.0.0
  html: ^0.15.0

  # Video Player
  video_player: ^2.8.1
  
  # UI
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  envied: ^0.5.4+1
  video_player_win: ^3.2.2
  scrollable_positioned_list:
  palette_generator: ^0.3.3
  bitsdojo_window: ^0.1.5
  window_manager: ^0.3.9

  # Shareable Card for stats
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  path_provider: ^2.1.2 #temporary save image

  # Online Stream
  # youtube_explode_dart: ^2.5.3 #To hunt for audio on YouTube without an API key.
  soundcloud_explode_dart: ^1.1.0
  just_audio_media_kit: 2.1.0 # Replaces default just_audio_windows backend
  media_kit: ^1.1.0
  media_kit_libs_video: ^1.0.0

  # Youtube Parser
  permission_handler: ^11.0.0
  youtube_explode_dart: ^2.0.2
  # ffmpeg_kit_flutter_new_gpl: ^1.6.5

  # Utilities
  uuid: ^4.3.3
  ffi: ^2.1.0

  # Databases
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # For multi-platform
  smtc_windows: ^1.1.0
  windows_taskbar: ^1.1.2

  # Firebase
  # Firebase REMOVED for PocketBase Migration
  # firebase_core: ^3.0.0
  # firebase_auth: ^5.0.0
  # cloud_firestore: ^5.0.0
  device_info_plus: ^12.3.0
  crypto: ^3.0.7
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  pocketbase: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Isar Database
  build_runner: ^2.4.8        # Runs the code generator
  isar_generator: ^3.1.0+1    # Generates the database code
  envied_generator: ^0.5.4+1
  
  # Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_source.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon_source.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/binaries/